language: ruby
before_install:
  - "gem install bundler -v '~> 1.5, != 1.5.0'"
rvm:
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-19mode
  - rbx-2.1.1
notifications:
  email:
    recipients:
      - tp@tiredpixel.com
matrix:
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2.1.1
